### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by alphaleadership** [SpeckyYT/waifulabs#2]
C:\Users\Collegien\node_modules\waifulabs\src\fetch.js:21
    .catch(() => {throw new Error(errorUnex)});
                        ^

Error: Unexpected Error occurred (parameters may be wrong)
    at C:\Users\Collegien\node_modules\waifulabs\src\fetch.js:21:25
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async C:\Users\Collegien\Documents\GitHub\wcreatormass\test.js:9:20

**Comment by SpeckyYT** [comment]
I can't really know what's wrong with that if you don't provide the code nor the input to the parameters.

**Comment by SpeckyYT** [comment]
API related, not module related.
